// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Register custom controllers
import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import CarouselFormController from "./carousel_form_controller"
application.register("carousel-form", CarouselFormController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageGridModalController from "./image_grid_modal_controller"
application.register("image-grid-modal", ImageGridModalController)

import MapController from "./map_controller"
application.register("map", MapController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import SignupFormController from "./signup_form_controller"
application.register("signup-form", SignupFormController)

import TaskDropdownController from "./task_dropdown_controller"
application.register("task-dropdown", TaskDropdownController)

// Register the animated-number controller
import AnimatedNumberController from "stimulus-animated-number";
application.register("animated-number", AnimatedNumberController);
