// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HideShowPasswordController from "./hide_show_password_controller"
application.register("hide-show-password", HideShowPasswordController)

import ImageGridModalController from "./image_grid_modal_controller"
application.register("image-grid-modal", ImageGridModalController)
